# Generated by Django 4.1.3 on 2022-12-05 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('dish_type', models.CharField(choices=[('SL', 'Salad'), ('FC', 'First course'), ('MC', 'Main course'), ('DS', 'Dessert'), ('BV', 'Beverage'), ('BK', 'Bakery')], default='SL', max_length=2)),
                ('tags', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('BL', 'Blocked')], default='AC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('BL', 'Blocked')], default='AC', max_length=2)),
                ('faves', models.TextField(default='')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipeblog.user'),
        ),
    ]
