# Generated by Django 4.1.3 on 2022-12-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeblog', '0002_recipe_user_delete_author_recipe_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['registration_date']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='picture',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps_to_complete',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dish_type',
            field=models.CharField(choices=[('SL', 'Салат'), ('FC', 'Первое'), ('MC', 'Второе'), ('DS', 'Десерт'), ('BV', 'Напиток'), ('BK', 'Выпечка')], default='SL', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='faves',
            field=models.TextField(blank=True, default=''),
        ),
    ]
