# Generated by Django 4.1.3 on 2023-02-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeblog', '0003_alter_user_options_recipe_description_recipe_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='user@user.com', max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='user@user.com', max_length=30),
            preserve_default=False,
        ),
    ]
