# Generated by Django 4.1.3 on 2023-03-25 01:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeblog', '0003_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_likes',
            field=models.ManyToManyField(related_name='recipe_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
