# Generated by Django 4.1.3 on 2023-03-30 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeblog', '0004_recipe_recipe_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='favs',
            field=models.ManyToManyField(blank=True, related_name='recipe_favs', to=settings.AUTH_USER_MODEL),
        ),
    ]
