# Generated by Django 4.1.3 on 2023-03-31 01:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeblog', '0005_remove_recipe_likes_recipe_favs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_likes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(related_name='recipe_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
