# Generated by Django 4.1.3 on 2023-03-31 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeblog', '0006_remove_recipe_recipe_likes_recipe_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='faves',
        ),
    ]
